### ISSUE TITLE
Program/AI not recognising wand movements/shapes

### ISSUE THREAD

**Issue by JouMyu** [mamacker/pi_to_potter#3]
Hi mamacker,

I have nearly completed the pi_to_potter project. I have the camera set up with one dot (the wand), the code rolling (I used trainedwpins.py) and even changed it from python 2 to 3 with proper indents and brackets. I have one small issue, the program does not recognise the shapes I draw with the wand. E.g, drawing a triangle does not trigger the corresponding spell to be printed in the terminal. I thought that was due to an insufficient picture set, but when trying to train said spell, the program would not recognise it either. I appreciate the time and effort you have put into this project and it seems to be a great improvement to the one on makezine.

Thanks in advance,
Jou-Myu

**Comment by mamacker** [comment]
Hi there,
  It sounds like its not training.  Are the training images being picked up at the start of the program?  Watch the output at the start of the program for any errors in finding the directory.
-Matt

**Comment by mamacker** [comment]
Closing out due to inactivity.
